os:
  - linux

language: rust

rust:
  - nightly

cache: cargo

script:
  - cargo test --verbose

before_deploy:
  - cargo build --release --verbose

deploy:
  provider: releases
  api_key:
    secure: NawaUClEm/c1C5BQSPQHvheBdPfJcOvrnektdKMzn2vpiumkEOP/M6SCZNa08kLyCWAvE1sfW+oRHsG+KGx14vrQO/usJNVMot2Bt0vTLrylpr2r8rGk2eIjmRaPNsqjyrFvRwDi3Jm1+T4qLNdwR5uuqZMjEHWmpd1MEmt1ahxPKD3T9BTigx7ovc0Tr1Er2PdjhdOD8/cMx/vGK4nEQrORFKopb0SXo2yBRq9uyo17Kgmfa3GMMhrdetJqWEuzOq8p+pOEsS26ygE1TEGk8x4YW/1k7eVUxRK4RDYjTF82eiMqL9WKJyruKwdJCCrqPa6E0EcRPYqP/B+JBc0BEZznV78vK1BpzOxci6HwtGs1sXhQ7isEHfbb1VKaLP8b2v7StBadPtme5wPjaWx+/jzENKctZtVvMA3321vEE1SMvhEJtUE6KatMgankP8jgEnXbQ0uDA/+uImqodObmueAFn0zbOQWfS4jlbNwSpHWKzuslxoePJHFGsda0wAXaDMVlgMqfjDvFpstlzBnfPnc8Sd6dyot4VIeTKjuOWh6FBlBq3ConlLZTopTCK62gnfwaekKWtmzUV9V1UiOKAa01G6Lggxy/WH8gyuOC10olsKSzBZJjzFVCWfBUZQJqjFPPTkkwzyPeSp+j7lKLZ3gRirqlb8xH80obIJMNVx0="
  file: "target/release/core"
  skip_cleanup: true
  on:
    tags: true
