os:
  - linux

language: rust

rust:
  - nightly

cache: cargo

script:
  - cargo test --verbose

before_deploy:
  - cargo build --release --verbose

deploy:
  provider: releases
  api_key:
    secure: SB8xTZl87mYZEakSiurOIsTuDzpA4zWnOzZgom7TkLY0Uen6mEG9yCmjcy56jzK9UwLYUH6g9EECninlXINeytKsdHLcSDMT4dbfAW3ymg9jCETbc86wmaeoBCoKQBp9JDAgFBO+RDCRW0Y7Im3iIxPq6Fv4Syy/0pxs/cZuWUd12OKTW7O9/X07viq4BU64GrV9Fxm4Mpn9gZoLmiRh24kGmI1ZilvJDyZkOvdYUCpVyFYPA0WBIc9GZRxw37xJlhBnTQKc7pWiWiQCAt9uQD29u2QfVzAXYWxdUfKtqjEv7g6jfSV0oGLasF105wyXWBjuAqFs4lIbcjeCJXn4UlWeOFt9mapleSsPAUSYiFkOsgrYUdJdWbzgWiQwasSmawDAKTim3DoefByo6+AVwlhQfeUSaATgC5GikMohhtJtMzV7yqpAu9YXb0zlrcB3UPyHFRFxFLd48KP+aM3t0dT+GsDt3pgTvianqUAeiQ69UK4yuZLE9cAiRRSYhZU6QTmAVFQDe4CqwVUbbdJscL9MWwcJ9DRWgGwnqPPcdAOL1O5NOL914CgiZe6to6far4MLl01IVtcZDQKe9n+DLRT1KtQ8FTSESK8kA24Z07ZUcU1X6yyi+7czfgx3fgdHAF3UENmZ/vFKdqE2rqiscvXHsoCiFVKuG956Ziiz5qg=
  file: "target/release/core"
  skip_cleanup: true
  on:
    tags: true
