os:
  - linux

language: rust

rust:
  - nightly

cache: cargo

script:
  - cargo test --verbose

before_deploy:
  - cargo build --release --verbose

deploy:
  provider: releases
  api_key:
    secure: NEW3WlPKw+qXjeyVF8+j79hOSHL34iL/YEgClrbv0uiRJPVfVHneeZN7eD6GHsfvFwJDOvKnarhZZJNFdsnyTTvzY0bsQqfueBQz+yxWY0oJyE1At/ZPAG9yWBN4Abe/NqkkfBVhW02akfWoxuDNY14+uXA/m+0XTePGP3t3ZamU4EeWaN/DJU6G/Ib4XFI8JGWM5x9ZG8dsT+1A03s0O52ZrfaMr69QvHhpvAtMAzay/j4X4ZEDOO14ScF+O5Jxr3um5Vws9x55PipF6rjTEKMPce68emGZAnTHMAZEOfOlNCWlDMLZvx3PGelAHTqLB8bgiZT7iQW7rMSsNmqO5Jat+Efu9lOcflLoHxR4lyZgfr8FgJQDLO6z+C68hVPWziEO+E6ckxxCg+DEM7ZcxPu6nEmm9VNy8zR6Cnornsti2mCZDuCu5l0mPFtK8LjqJEb1PHZZMUKybSB+PSlwQ3MtgAVo0OjEyMd8OX8fKQV0zaqgqOyOncetW8MeG0FBNFUSy0c5vSwhKDYTrP4H+g0viGf0L6vapvaf/iian//WSDq+DRetk1W5GMTbTGn87+JQkPXFs0tBjlq+05Pf6HbNtKLioTitvFf4oMkDj0h5PPjRBH2bhQi2u1nXZeLHJQRy5yejN55RNydSvknTE6aiUe0j2JDCdmKIiFi6MXw=
  file: target/release/core
  skip_cleanup: true
  on:
    tags: true
