environment:
  matrix:
  - TARGET: i686-pc-windows-msvc
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - set PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

cache:
  - 'C:\Users\appveyor\.cargo'

build: false

test_script:
  - cargo test --target %TARGET%

before_deploy:
  - cargo build --release
  - ps: Push-AppveyorArtifact target\release\core.exe

deploy:
  description: 'Collabook Core for Windows'
  provider: GitHub
  auth_token:
    secure: B9mugMz4P5+/VgjwGzaPFHO8UfJizn8Dx5d2VDlcOgM5PcJCorHu2Fj0eKAoXJMb
  artifact: target\release\core.exe
  on:
    appveyor_repo_tag: true
