environment:
  matrix:
  - TARGET: i686-pc-windows-msvc
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain nightly -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;c:\cygwin\bin
  - rustc -V
  - cargo -V

build: false

cache:
  - 'C:\Users\appveyor\.cargo'

test_script:
  - cargo test --target %TARGET%
